<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>WolfPatcher.IntegrationHarness</AssemblyName>
    <RootNamespace>WolfPatcher.IntegrationHarness</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/WolfPatcher.Core/WolfPatcher.Core.csproj" />
  </ItemGroup>
</Project>
